// Code generated by protoc-gen-go. DO NOT EDIT.
// source: postbox.proto

package postbox

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Letter struct {
	ID                   uint64   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Ipaddr               string   `protobuf:"bytes,3,opt,name=ipaddr,proto3" json:"ipaddr,omitempty"`
	Time                 int64    `protobuf:"varint,4,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Letter) Reset()         { *m = Letter{} }
func (m *Letter) String() string { return proto.CompactTextString(m) }
func (*Letter) ProtoMessage()    {}
func (*Letter) Descriptor() ([]byte, []int) {
	return fileDescriptor_122c65ebf26d1b04, []int{0}
}

func (m *Letter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Letter.Unmarshal(m, b)
}
func (m *Letter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Letter.Marshal(b, m, deterministic)
}
func (m *Letter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Letter.Merge(m, src)
}
func (m *Letter) XXX_Size() int {
	return xxx_messageInfo_Letter.Size(m)
}
func (m *Letter) XXX_DiscardUnknown() {
	xxx_messageInfo_Letter.DiscardUnknown(m)
}

var xxx_messageInfo_Letter proto.InternalMessageInfo

func (m *Letter) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Letter) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *Letter) GetIpaddr() string {
	if m != nil {
		return m.Ipaddr
	}
	return ""
}

func (m *Letter) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func init() {
	proto.RegisterType((*Letter)(nil), "postbox.Letter")
}

func init() { proto.RegisterFile("postbox.proto", fileDescriptor_122c65ebf26d1b04) }

var fileDescriptor_122c65ebf26d1b04 = []byte{
	// 124 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0xc8, 0x2f, 0x2e,
	0x49, 0xca, 0xaf, 0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x72, 0x95, 0xa2, 0xb8,
	0xd8, 0x7c, 0x52, 0x4b, 0x4a, 0x52, 0x8b, 0x84, 0xf8, 0xb8, 0x98, 0x3c, 0x5d, 0x24, 0x18, 0x15,
	0x18, 0x35, 0x58, 0x82, 0x98, 0x3c, 0x5d, 0x84, 0x44, 0xb8, 0x58, 0xcb, 0x12, 0x73, 0x4a, 0x53,
	0x25, 0x98, 0x14, 0x18, 0x35, 0x38, 0x83, 0x20, 0x1c, 0x21, 0x31, 0x2e, 0xb6, 0xcc, 0x82, 0xc4,
	0x94, 0x94, 0x22, 0x09, 0x66, 0xb0, 0x30, 0x94, 0x27, 0x24, 0xc4, 0xc5, 0x52, 0x92, 0x99, 0x9b,
	0x2a, 0xc1, 0xa2, 0xc0, 0xa8, 0xc1, 0x1c, 0x04, 0x66, 0x27, 0xb1, 0x81, 0xed, 0x32, 0x06, 0x04,
	0x00, 0x00, 0xff, 0xff, 0x60, 0x33, 0x0d, 0x43, 0x7c, 0x00, 0x00, 0x00,
}
